language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script
    script: npm run build && now --public --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true